name: inundation_toolbox
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - black
  - contextily
  - GDAL
  - geopandas
  - jupyter
  - lxml
  - matplotlib
  - momepy
  - netCDF4
  - numpy
  - pandas
  - pandera-geopandas
  - pandera-io
  - pydantic==1.8.2
  - rasterio
  - rasterstats
  - scipy
  - shapely==1.8.5
  - xarray
  - pip
  - pip:
    - imod
    - ipympl
    - isort
    - matplotlib_scalebar
    - meshkernel>=2.0
    - tqdm
    - ugrid
  